### PR TITLE
Allow people to add custom branches

### PR DESCRIPTION
**Pull request by aviskarkc10**
1. Wrote a `for...loop` for checking whether a branch should be ignored.
2. Now users can create a `.ignore` file in their directory. If such file is found, we will append it to the array of default ignored branches and ignore commits to those branches as well.

### CODE REVIEW

**Comment by aviskarkc10** [comment]
Fixed

**Comment by sbimochan** [comment]
let's use 4 tabs indent instead of 8.
sample .ignore file content and we can also just push that file too.

**Comment by aviskarkc10** [comment]
The `.ignore` doesn't need to be copied. When would we need it?

**Comment by aviskarkc10** [comment]
check #9

**Pull request merged**
